version: '3'

volumes:
  chat_postgres_volume:

services:
  chat-pg:
    image: postgres:14-alpine3.17
    container_name: chat_postgres
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - chat_postgres_volume:/var/lib/postgresql/data